source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!
#inhibit_all_warnings!

def common
    pod 'WeexSDK', '0.16.0'
    pod 'WXDevtool', '0.15.1'
    pod 'SDWebImage', '3.7.5'
    pod 'SocketRocket', '0.4.2'
    pod 'ATSDK-Weex', '0.0.1'
    pod 'WeexKdp', :path=>'../../'
    pod 'WeexPluginLoader'
    pod 'PlayKit'
end

target 'WeexDemo' do
    common
end


pre_install do |installer|
    def installer.verify_no_static_framework_transitive_dependencies; end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
    	target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
